### ISSUE TITLE
Problem with MiniColors field

### ISSUE THREAD

**Issue by viamage** [gergo85/oc-form-widgets#1]
Hello,
I installed your plugin in a fresh October instance and tried to use mini colors field with:

```
    rgb:
        label: viamage.fingernails::lang.colours.rgb
        type: minicolors
        control: wheel
```
it doesn't seem to be working though and it's spamming jQuery migrate errors in console:

![img](https://i.viamage.com/jz/screenshot-2019-03-25-13-03-13.png)

I installed plugin by cloning it into indikator/form and issuing `php october:up`

Is it something you can reproduce or is there something I'm missing?
